print("You approach the Bridge of Death. It is old, almost collapsing, but it is also your only hope of crossing the Bridge of Eternal Peril.")
print("Look, there's the old man from scene 24.")
print("What is he doing here?")
print("He is the keeper of the Bridge of Death.")
print("He asks each traveler five... no, three questions.")
print("He who answers the five - THREE questions! Three questions - may cross in safety.")
print("What if you get a question wrong?")
print("Then you are cast into the Gorge of Eternal Peril!")
print("The gatekeeper asks:")
nm = input("What is your name?")
print("The gatekeeper asks:")
qst = input ("What is your quest?")
print("The gatekeeper asks:")
cor = input("What is your favorite color:")
print("The gatekeeper says:")
print("You are")
print(nm)
print("Your quest is")
print(qst)
print("Your favorite color is")
print(cor)
print("The gatekeeper asks:")
swl = input ("What  is the airspeed velocity of an unladen swallow?")
print("African or South American? I don't know that!")
print("...the gatekeeper has been flung into the gorge...")